version: "3.8"

services: 
  runner:
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=Qwerty@123"
      - "MYSQL_MASTER1_PASSWORD=qwerty@123"
      - "MYSQL_MASTER2_PASSWORD=qwerty@123"
      - "MYSQL_REPLICATION_USER=replica"
      - "MYSQL_REPLICATION_PASSWORD=Qwerty@123"
    depends_on: 
      - mysqlmaster1
      - mysqlmaster2
  mysqlmaster1:
    container_name: mysqlmaster1
    image: mysql:latest
    volumes: 
      - ./conf/master1.cnf:/etc/mysql/my.cnf
      - ./data/master1:/var/lib/mysql
    ports: 
      - 3307:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "Qwerty@123"
      MYSQL_DATABASE: "avi_db"
      MYSQL_USER: "replica"
      MYSQL_PASSWORD: "Qwerty@123"
    networks:
      mysql-ms-network:
        ipv4_address: 172.25.0.101

  mysqlmaster2:
    container_name: mysqlmaster2
    image: mysql:latest
    volumes: 
      - ./conf/master2.cnf:/etc/mysql/my.cnf
      - ./data/master2:/var/lib/mysql
    ports: 
      - 3308:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "Qwerty@123"
      MYSQL_DATABASE: "avi_db"
      MYSQL_USER: "replica"
      MYSQL_PASSWORD: "Qwerty@123"
    networks:
      mysql-ms-network:
        ipv4_address: 172.25.0.102

    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  mysql-ms-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
